REM INSERTING into MERCHANTS
SET DEFINE OFF;
Insert into MERCHANTS (MERCHANT_NAME) values ('Oak Foods');
Insert into MERCHANTS (MERCHANT_NAME) values ('Rabbit Co.');
Insert into MERCHANTS (MERCHANT_NAME) values ('Aura');
Insert into MERCHANTS (MERCHANT_NAME) values ('Bridgelectrics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Sharkfinetworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Surgesystems');
Insert into MERCHANTS (MERCHANT_NAME) values ('Globaviations');
Insert into MERCHANTS (MERCHANT_NAME) values ('Pinnaclehut');
Insert into MERCHANTS (MERCHANT_NAME) values ('Cloudphone');
Insert into MERCHANTS (MERCHANT_NAME) values ('Phantomntechs');
Insert into MERCHANTS (MERCHANT_NAME) values ('Enigma Entertainment');
Insert into MERCHANTS (MERCHANT_NAME) values ('Witch Technologies');
Insert into MERCHANTS (MERCHANT_NAME) values ('Fire Intelligence');
Insert into MERCHANTS (MERCHANT_NAME) values ('Oakoms');
Insert into MERCHANTS (MERCHANT_NAME) values ('Whirlwindustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Sawwares');
Insert into MERCHANTS (MERCHANT_NAME) values ('Luckytronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Freakcast');
Insert into MERCHANTS (MERCHANT_NAME) values ('Grizzlyworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Heartwell');
Insert into MERCHANTS (MERCHANT_NAME) values ('Flux Corporation');
Insert into MERCHANTS (MERCHANT_NAME) values ('Buzzy Bee Softwares');
Insert into MERCHANTS (MERCHANT_NAME) values ('Trek Systems');
Insert into MERCHANTS (MERCHANT_NAME) values ('Goldustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('North Starporation');
Insert into MERCHANTS (MERCHANT_NAME) values ('Houndnavigations');
Insert into MERCHANTS (MERCHANT_NAME) values ('Yeworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Thunderaid');
Insert into MERCHANTS (MERCHANT_NAME) values ('Herbtime');
Insert into MERCHANTS (MERCHANT_NAME) values ('Griffingate');
Insert into MERCHANTS (MERCHANT_NAME) values ('Jungle');
Insert into MERCHANTS (MERCHANT_NAME) values ('Prime Corporation');
Insert into MERCHANTS (MERCHANT_NAME) values ('Thor Intelligence');
Insert into MERCHANTS (MERCHANT_NAME) values ('Rosecurity');
Insert into MERCHANTS (MERCHANT_NAME) values ('Orco');
Insert into MERCHANTS (MERCHANT_NAME) values ('Smilectronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Happindustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Ghostfruit');
Insert into MERCHANTS (MERCHANT_NAME) values ('Happyfly');
Insert into MERCHANTS (MERCHANT_NAME) values ('Goldbridge');
Insert into MERCHANTS (MERCHANT_NAME) values ('Vertex Limited');
Insert into MERCHANTS (MERCHANT_NAME) values ('Beta Entertainment');
Insert into MERCHANTS (MERCHANT_NAME) values ('Bluff Acoustics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Ridgeco');
Insert into MERCHANTS (MERCHANT_NAME) values ('Goldustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Happindustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('White Wolfoods');
Insert into MERCHANTS (MERCHANT_NAME) values ('Firespace');
Insert into MERCHANTS (MERCHANT_NAME) values ('Ghoststar');
Insert into MERCHANTS (MERCHANT_NAME) values ('Ravenscape');
Insert into MERCHANTS (MERCHANT_NAME) values ('Vortex Corp');
Insert into MERCHANTS (MERCHANT_NAME) values ('Tucan Motors');
Insert into MERCHANTS (MERCHANT_NAME) values ('Radiant Arts');
Insert into MERCHANTS (MERCHANT_NAME) values ('Signetworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Witchystems');
Insert into MERCHANTS (MERCHANT_NAME) values ('Heartelligence');
Insert into MERCHANTS (MERCHANT_NAME) values ('Honeydustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Smileway');
Insert into MERCHANTS (MERCHANT_NAME) values ('Chiefsearch');
Insert into MERCHANTS (MERCHANT_NAME) values ('Dinoshine');
Insert into MERCHANTS (MERCHANT_NAME) values ('Melon Records');
Insert into MERCHANTS (MERCHANT_NAME) values ('Pixel Systems');
Insert into MERCHANTS (MERCHANT_NAME) values ('Raptor Co.');
Insert into MERCHANTS (MERCHANT_NAME) values ('Junglectics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Pyramidustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Bluetronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Joytechs');
Insert into MERCHANTS (MERCHANT_NAME) values ('Dynamicmart');
Insert into MERCHANTS (MERCHANT_NAME) values ('Apexsys');
Insert into MERCHANTS (MERCHANT_NAME) values ('Hatchway');
Insert into MERCHANTS (MERCHANT_NAME) values ('Alp Electronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Yellow Brews');
Insert into MERCHANTS (MERCHANT_NAME) values ('Phantom Brews');
Insert into MERCHANTS (MERCHANT_NAME) values ('Aprico');
Insert into MERCHANTS (MERCHANT_NAME) values ('Whiteoutwares');
Insert into MERCHANTS (MERCHANT_NAME) values ('Turtletainment');
Insert into MERCHANTS (MERCHANT_NAME) values ('Stormedia');
Insert into MERCHANTS (MERCHANT_NAME) values ('Oceanspace');
Insert into MERCHANTS (MERCHANT_NAME) values ('Forestlife');
Insert into MERCHANTS (MERCHANT_NAME) values ('Shadewalk');
Insert into MERCHANTS (MERCHANT_NAME) values ('Apple Sports');
Insert into MERCHANTS (MERCHANT_NAME) values ('Red Corporation');
Insert into MERCHANTS (MERCHANT_NAME) values ('Granite Coms');
Insert into MERCHANTS (MERCHANT_NAME) values ('Luckytronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Elecoms');
Insert into MERCHANTS (MERCHANT_NAME) values ('Seawares');
Insert into MERCHANTS (MERCHANT_NAME) values ('Yeworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Boarshow');
Insert into MERCHANTS (MERCHANT_NAME) values ('Woodhead');
Insert into MERCHANTS (MERCHANT_NAME) values ('Flowerstar');
Insert into MERCHANTS (MERCHANT_NAME) values ('Phantom Motors');
Insert into MERCHANTS (MERCHANT_NAME) values ('Rabbit Corp');
Insert into MERCHANTS (MERCHANT_NAME) values ('Omega Electronics');
Insert into MERCHANTS (MERCHANT_NAME) values ('Apexi');
Insert into MERCHANTS (MERCHANT_NAME) values ('Robinetworks');
Insert into MERCHANTS (MERCHANT_NAME) values ('Mermedia');
Insert into MERCHANTS (MERCHANT_NAME) values ('Fjordustries');
Insert into MERCHANTS (MERCHANT_NAME) values ('Blossomstone');
Insert into MERCHANTS (MERCHANT_NAME) values ('Tigertime');
Insert into MERCHANTS (MERCHANT_NAME) values ('Sunstar');

Commit;

