REM INSERTING into MERCHANTS
SET DEFINE OFF;
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (1,'Oak Foods');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (2,'Rabbit Co.');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (3,'Aura');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (4,'Bridgelectrics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (5,'Sharkfinetworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (6,'Surgesystems');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (7,'Globaviations');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (8,'Pinnaclehut');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (9,'Cloudphone');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (10,'Phantomntechs');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (11,'Enigma Entertainment');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (12,'Witch Technologies');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (13,'Fire Intelligence');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (14,'Oakoms');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (15,'Whirlwindustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (16,'Sawwares');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (17,'Luckytronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (18,'Freakcast');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (19,'Grizzlyworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (20,'Heartwell');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (21,'Flux Corporation');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (22,'Buzzy Bee Softwares');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (23,'Trek Systems');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (24,'Goldustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (25,'North Starporation');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (26,'Houndnavigations');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (27,'Yeworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (28,'Thunderaid');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (29,'Herbtime');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (30,'Griffingate');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (31,'Jungle');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (32,'Prime Corporation');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (33,'Thor Intelligence');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (34,'Rosecurity');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (35,'Orco');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (36,'Smilectronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (37,'Happindustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (38,'Ghostfruit');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (39,'Happyfly');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (40,'Goldbridge');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (41,'Vertex Limited');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (42,'Beta Entertainment');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (43,'Bluff Acoustics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (44,'Ridgeco');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (45,'Goldustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (46,'Happindustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (47,'White Wolfoods');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (48,'Firespace');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (49,'Ghoststar');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (50,'Ravenscape');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (51,'Vortex Corp');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (52,'Tucan Motors');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (53,'Radiant Arts');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (54,'Signetworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (55,'Witchystems');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (56,'Heartelligence');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (57,'Honeydustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (58,'Smileway');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (59,'Chiefsearch');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (60,'Dinoshine');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (61,'Melon Records');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (62,'Pixel Systems');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (63,'Raptor Co.');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (64,'Junglectics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (65,'Pyramidustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (66,'Bluetronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (67,'Joytechs');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (68,'Dynamicmart');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (69,'Apexsys');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (70,'Hatchway');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (71,'Alp Electronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (72,'Yellow Brews');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (73,'Phantom Brews');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (74,'Aprico');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (75,'Whiteoutwares');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (76,'Turtletainment');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (77,'Stormedia');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (78,'Oceanspace');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (79,'Forestlife');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (80,'Shadewalk');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (81,'Apple Sports');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (82,'Red Corporation');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (83,'Granite Coms');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (84,'Luckytronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (85,'Elecoms');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (86,'Seawares');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (87,'Yeworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (88,'Boarshow');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (89,'Woodhead');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (90,'Flowerstar');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (91,'Phantom Motors');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (92,'Rabbit Corp');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (93,'Omega Electronics');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (94,'Apexi');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (95,'Robinetworks');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (96,'Mermedia');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (97,'Fjordustries');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (98,'Blossomstone');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (99,'Tigertime');
Insert into MERCHANTS (MERCHANT_ID,MERCHANT_NAME) values (100,'Sunstar');

Commit;

